version: '3.8'

services:
  postgres:
    image: 'goodrequestcom/internship_postgres:latest'
    ports:
      - "55432:5432"
  postgres_test:
    image: 'goodrequestcom/internship_postgres:latest'
    ports:
      - "25432:5432"